<div class="footer-index" id="footer">
   <div class="footer-index-inner">
      <div class="footer-left">
         <div>© 2018 <a href="https://nuls.io" target="_blank">Nuls</a></div>
         <div>Documentation licensed under <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></div>
         <div>Power by <a href="https://hexo.io" target="_blank">HEXO</a></div>
      </div>
      <div class="footer-middle">
        <div>
          <a href="https://twitter.com/{{ config.twitter }}" target="_blank"><i class="footer-icon1"></i></a>
        </div>
        <div>
         <a href="https://www.reddit.com/{{ config.reddit }}" target="_blank"><i class="footer-icon2"></i></a>
        </div>
        <div>
          <a href="https://t.me/{{ config.telegram }}" target="_blank"><i class="footer-icon3"></i></a>
        </div>
        <div>
           <a href="https://steemit.com/@{{ config.steemit }}" target="_blank"><i class="footer-icon4"></i></a>
        </div>
        <div>
          <a href="https://github.com/{{ config.github }}" target="_blank"><i class="footer-icon5"></i></a>
        </div>
        <div>
          <a href="https://www.facebook.com/{{ config.facebook }}" target="_blank"><i class="footer-icon6"></i></a>
        </div>
        <div>
          <a href="https://join.slack.com/{{ config.slack }}" target="_blank"><i class="footer-icon7"></i></a>
        </div>
        <div>
          <a href="https://gitter.im/{{ config.gitter }}" target="_blank"><i class="footer-icon8"></i></a>
        </div>
      </div>
   </div>
</div>